apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    uid: aegis-redis-ds
    access: proxy
    url: redis://aegis-redis:6379
    isDefault: false
    editable: true
    jsonData:
      client: standalone
      dbIndex: 0
